function(cmake_helpers_option name default description)
  set(_proposed_values ${ARGN})
  set(${name} ${default} CACHE STRING ${description})
  if(NOT default IN_LIST _proposed_values)
    list(APPEND _proposed_values ${default})
  endif()
  set_property(CACHE ${name} PROPERTY STRINGS ${_proposed_values})
endfunction()
