function(cmake_helpers_option name default description proposed_values)
  set(${name} ${default} CACHE STRING ${description})
  if(NOT default IN_LIST proposed_values)
    list(APPEND proposed_values ${default})
  endif()
  set_property(CACHE ${name} PROPERTY STRINGS ${proposed_values})
endfunction()
